# Generated by Django 3.1.1 on 2021-04-24 16:20

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_the_audiobook', models.CharField(max_length=100)),
                ('author_of_audiobook', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'audiobook',
                'verbose_name_plural': 'audiobooks',
                'db_table': 'audiobook',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_podcast', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('host', models.CharField(max_length=100)),
                ('participants', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1010, null=True, size=10)),
            ],
            options={
                'verbose_name': 'podcast',
                'verbose_name_plural': 'podcasts',
                'db_table': 'podcast',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_song', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
                'db_table': 'song',
            },
        ),
    ]
